name: Build
on:
    pull_request:
        branches: 
            - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node: ['15', '16']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
               node-version: ${{ matrix.node }}
            - uses: sonarsource/sonarqube-scan-action@master
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - run: npm install
            - run: npm test
            - run: node ./soma.js
            
            - name: Set up QEMU # responsável por rodar o Docker em diversas arquiteturas
              uses: docker/setup-qemu-action@v2
                  
            