name: fullcycle-desafiocisonarcloud
on:
    pull_request:
        branches: 
            - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node: ['14', '15', '16']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
               node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm test
            - run: node ./soma.js

            