name: ci-fullcycle
on:
    pull_request:
        branches: 
            - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node: ['15', '16']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
               node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm test
            - run: node ./soma.js

            - name: SonarCloud Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}